
`timescale 1ns/1ns
// --------------------------------------------------------------------
// Netlist generated by Diamond Version 0.0.0 ipgen -n I2C_Core -lang verilog -arch ICE40UL -type serialbus -freq 150 -i2c left -i2c_general_call_enable none -i2c_wakeup_enable none -i2c_iobuffer both -i2c_rate_left 100 -i2c_rate_right 100 -i2c_addr_left 10000 -i2c_addr_right 10000 -i2c_arbitration_lost none -i2c_txrx_ready none -i2c_overrun none -i2c_general_call none -i2c_sda_input both -i2c_sda_output none -i2c_fifo_enable none -i2c_fifo_clkstr none -i2c_fifo_rxalmostf_left 31 -i2c_fifo_txalmoste_left 1 -i2c_fifo_rxalmostf_right 31 -i2c_fifo_txalmoste_right 1 -i2c_fifo_intr_gc none -i2c_fifo_intr_nack none -i2c_fifo_mrxrdy none -i2c_fifo_intr_arbit none -i2c_fifo_txsync none -i2c_fifo_txunder none -i2c_fifo_rxover none 
// >>>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// --------------------------------------------------------------------
// Copyright (c) 2014 by Lattice Semiconductor Corporation
// --------------------------------------------------------------------
//
// Permission:
//
//   Lattice Semiconductor grants permission to use this code for use
//   in synthesis for any Lattice programmable logic product.  Other
//   use of this code, including the selling or duplication of any
//   portion is strictly prohibited.
//
// Disclaimer:
//
//   This VHDL or Verilog source code is intended as a design reference
//   which illustrates how these types of functions can be implemented.
//   It is the user's responsibility to verify their design for
//   consistency and functionality through the use of formal
//   verification methods.  Lattice Semiconductor provides no warranty
//   regarding the use or functionality of this code.
//
// --------------------------------------------------------------------
//
//               Lattice Semiconductor Corporation
//               5555 NE Moore Court
//               Hillsboro, OR 97214
//               U.S.A
//
//               web: http://www.latticesemi.com/
//               email: techsupport@latticesemi.com
//   
// --------------------------------------------------------------------
//
//  Project:           iCE ThunderBolt
//  File:              BoltHardIPinit.v
//  Title:             Hard IP initialization
//  Description:       Initializes the Hard IP upon power-up or on command (IPLOAD)
//                      using data (`include file) provided by the  
//                      Module Generator tool.
//
// --------------------------------------------------------------------
//
//------------------------------------------------------------
// Notes:
//
//  Port index '0' is Upper Right I2C block, '1' is Upper Left I2C block
//  Default implementation utilizes LUTs to store the Initialization Data.
//  Alternatively, an EBR structure could be utilized, trading LUTs for EBR if necessary.
//
//------------------------------------------------------------
// Development History:
//
//   __DATE__ _BY_ _REV_ _DESCRIPTION___________________________
//   05/10/13  SH  0.00  Initial Lightning Design
//   05/02/14  SH  1.00  Modified for Bolt
//   05/23/14  CW  1.01  Updated status flags
//   07/15/14  CW  1.02  Changed "SB_HSOSC" to "SB_HFOSC"
//------------------------------------------------------------
// Dependencies:
//
// - Instantiates iCE Bolt Hard IP:  User I2C, HFOSC
// - Requires file "ip_defines.vh" defining module name and port defines.
// - Requires file "register_inits.vh" defining register initialization data.
//
//------------------------------------------------------------
// ---------- Design Unit Header ---------- //
//----------------------------------------------------------------------------
//                                                                          --
//                         ENTITY DECLARATION                               --
//                                                                          --
//----------------------------------------------------------------------------
module I2C_Core (
    // Chip Interface
    inout wire I2C1_SCL, 
    inout wire I2C1_SDA, 
    // Fabric Interface
    input wire RST, 
    // Asynchronous Reset, for Init_SSM
    input wire hard_FIFORST, 
    // Synchronous Reset, for Hard IP core
    input wire IPLOAD, 
    // Rising Edge triggers Hard IP Configuration
    output wire IPDONE, 
    // 1: Hard IP Configuration is complete
    input wire SBCLKi, 
    // System bus interface to both Hard IP blocks
    input wire SBWRi, 
    //  This bus is available when IPDONE = 1
    input wire [1:0] SBCSi, 
    input wire SBSTBi, 
    input wire [3:0] SBADRi, 
    input wire [9:0] SBDATi, 
    output wire [9:0] SBDATo, 
    output wire SBACKo, 
    input wire ENACLKM, 
        
    // 1: Enable HFOSC
    input wire CLKHFPU, 
    // 1: Power up HFOSC
    input wire CLKCONF, 
    // Alternalt configuraton clock 
    input wire USE_HFOSC, 
    // 1: Use built-in HFOSC, 0: Use CLKCONF for configuration
    output wire CLKM, 
    // output of HFOSC
    output wire [1:0] SBSRWo, 
    output wire [1:0] I2CPIRQ, 
    output wire [1:0] I2CPWKUP, 
    output wire [1:0] TXAEMPTY, 
    output wire [1:0] TXEMPTY, 
    output wire [1:0] TXFULL, 
    output wire [1:0] RXEMPTY, 
    output wire [1:0] RXAFULL, 
    output wire [1:0] RXFULL, 
    output wire [1:0] I2CMRDCMPL) ;
    //----------------------------------------------------------------------------
    //                                                                          --
    //                       ARCHITECTURE DEFINITION                            --
    //                                                                          --
    //----------------------------------------------------------------------------
    //------------------------------
    // INTERNAL SIGNAL DECLARATIONS: 
    //------------------------------
    // parameters (constants)
    // wires (assigns)
    wire hard_SBCLKi ; 
    wire hard_SBWRi ; 
    wire [1:0] hard_SBCSi ; 
    wire hard_SBSTBi ; 
    wire [7:0] hard_SBADRi ; 
    wire [9:0] hard_SBDATi ; 
    wire hard0_SBACKo ; 
    wire hard1_SBACKo ; 
    wire [1:0] hard_ACKs ; 
    wire SBACKo_i ; 
    wire hard0_SBSRWo ; 
    wire hard1_SBSRWo ; 
    wire [9:0] hard0_SBDATo ; 
    wire [9:0] hard1_SBDATo ; 
    wire ssm_SBCLKi ; 
    wire ssm_SBWRi ; 
    wire [1:0] ssm_SBCSi ; 
    wire ssm_SBSTBi ; 
    wire [3:0] ssm_SBADRi ; 
    wire [9:0] ssm_SBDATi ; 
    wire HFOSC ; 
    wire I2C1_SCLo ; 
    wire I2C1_SCLoe ; 
    wire I2C1_SCLi ; 
    wire I2C1_SDAo ; 
    wire I2C1_SDAoe ; 
    wire I2C1_SDAi ; 
    // regs (always)
    reg [9:0] SBDATo_i ; 
    reg load_d1 ; 
    reg load_d2 ; 
    reg start ; 
    reg pup ; 
    reg run ; 
    reg [5:0] trans_count ; 
    reg IPDONE_i ; 
    reg sb_idle ; 
    reg strobe ; 
    //-------------------------------------//
    //-- assign (non-process) operations --//
    //-------------------------------------//
    parameter num_regs = 13 ; 
    wire [9:0] init_value [0:(num_regs - 1)] ; 
    wire [7:0] init_addr [0:(num_regs - 1)] ; 
    assign init_addr[0] = 8'b010001 ; 
    assign init_addr[1] = 8'b010100 ; 
    assign init_addr[2] = 8'b010101 ; 
    assign init_addr[3] = 8'b010010 ; 
    assign init_addr[4] = 8'b010011 ; 
    assign init_addr[5] = 8'b11111111 ; 
    assign init_addr[6] = 8'b11111111 ; 
    assign init_addr[7] = 8'b11111111 ; 
    assign init_addr[8] = 8'b11111111 ; 
    assign init_addr[9] = 8'b11111111 ; 
    assign init_addr[10] = 8'b11111111 ; 
    assign init_addr[11] = 8'b11111111 ; 
    assign init_addr[12] = 8'b11111111 ; 
    assign init_value[0] = 8'b10000000 ; 
    assign init_value[1] = 8'b010000 ; 
    assign init_value[2] = 8'b0 ; 
    assign init_value[3] = 118 ; 
    assign init_value[4] = 1 ; 
    assign init_value[5] = 8'b11111111 ; 
    assign init_value[6] = 8'b11111111 ; 
    assign init_value[7] = 8'b11111111 ; 
    assign init_value[8] = 8'b11111111 ; 
    assign init_value[9] = 8'b11111111 ; 
    assign init_value[10] = 8'b11111111 ; 
    assign init_value[11] = 8'b11111111 ; 
    assign init_value[12] = 8'b11111111 ; 
    // SYSTEM BUS multiplexing
    assign hard_SBCLKi = (IPDONE_i ? SBCLKi : ssm_SBCLKi) ; 
    assign hard_SBWRi = (IPDONE_i ? SBWRi : ssm_SBWRi) ; 
    assign hard_SBCSi = (IPDONE_i ? SBCSi : ssm_SBCSi) ; 
    assign hard_SBSTBi = (IPDONE_i ? SBSTBi : ssm_SBSTBi) ; 
    assign hard_SBADRi = (IPDONE_i ? SBADRi : ssm_SBADRi) ; 
    assign hard_SBDATi = (IPDONE_i ? SBDATi : ssm_SBDATi) ; 
    assign hard_ACKs = {hard1_SBACKo,hard0_SBACKo} ; // 
    assign SBACKo_i = (|hard_ACKs) ; 
    // Initialization SSM outputs
    assign ssm_SBCLKi = (USE_HFOSC ? HFOSC : CLKCONF) ; // SSM clock select
    assign ssm_SBWRi = 1 ; // All transaction are WRITE
    assign ssm_SBSTBi = strobe ; // 
    assign ssm_SBCSi = init_addr[trans_count][5:4] ; // use Chip Select to
    assign ssm_SBADRi = init_addr[trans_count][3:0] ; //  write SBADR
    assign ssm_SBDATi = init_value[trans_count] ; //   with init data
    //-------------------------------------//
    //---- always (process) operations ----//
    //-------------------------------------//
    // DATo mux
    //
    always
        @( SBCSi or  hard_ACKs)
        case (SBCSi)
        2'b10 : 
            SBDATo_i <=  hard1_SBDATo ;
        2'b01 : 
            SBDATo_i <=  hard0_SBDATo ;
        default : 
            SBDATo_i <=  10'b0 ;
        endcase 
    //   Initialization SSM control: Start, Run, Done
    //
    always
        @(posedge ssm_SBCLKi or posedge RST)
        if (RST) 
            begin
                load_d1 <=  0 ;
                load_d2 <=  0 ;
                start <=  0 ;
                pup <=  1 ;
                run <=  0 ;
                trans_count <=  0 ;
                IPDONE_i <=  0 ;
            end
        else
            begin
                load_d1 <=  (IPLOAD || pup) ;
                load_d2 <=  load_d1 ;
                start <=  (load_d1 && (!load_d2)) ;// rising-edge detection
                if (start) // clear power-up launch flag
                    pup <=  0 ;
                if (start) 
                    run <=  1 ;
                else
                    // start init sequence
                    if (IPDONE_i) //  clear when init complete
                        run <=  0 ;
                if (start) 
                    begin
                        // reset control upon Start
                        trans_count <=  0 ;
                        IPDONE_i <=  0 ;
                    end
                else
                    if ((init_addr[trans_count] == 8'b11111111)) 
                        begin
                            // DONE
                            IPDONE_i <=  1 ;
                        end
                    else
                        if (SBACKo_i) 
                            begin
                                // increment if not DONE
                                trans_count <=  (trans_count + 1) ;
                            end
            end
    //  System Bus transaction control
    //    Assert stb until EFB acknowledges with SBACKo
    //
    always
        @(posedge ssm_SBCLKi or posedge RST)
        begin
            if (RST) 
                begin
                    sb_idle <=  1 ;
                    strobe <=  0 ;
                end
            else
                begin
                    //  Assert stb signals to start SB transaction
                    if (sb_idle) 
                        begin
                            if (run) 
                            // Monitor SBACKo for end of transaction
                                begin
                                    strobe <= #(1)   1 ;// delay 1 ns to avoid simulation/hardware mismatch
                                    sb_idle <=  0 ;
                                end
                        end
                    else
                        begin
                            if ((SBACKo_i | (!run))) 
                                begin
                                    strobe <=  0 ;
                                    sb_idle <=  1 ;
                                end
                        end
                end
        end
    //-------------------------------------//
    //-------- output assignments  --------//
    //-------------------------------------//
    assign SBDATo = SBDATo_i ; 
    assign SBACKo = (SBACKo_i && IPDONE_i) ; 
    assign CLKM = HFOSC ; 
    assign IPDONE = IPDONE_i ; 
    assign SBSRWo = {hard1_SBSRWo,hard0_SBSRWo} ; 
    assign I2C1_SCL = (I2C1_SCLoe ? I2C1_SCLo : 1'bz) ; 
    assign I2C1_SCLi = I2C1_SCL ; 
    assign I2C1_SDA = (I2C1_SDAoe ? I2C1_SDAo : 1'bz) ; 
    assign I2C1_SDAi = I2C1_SDA ; 
    //-------------------------------------//
    //----- component instantiations ------//
    //-------------------------------------//
    SB_HFOSC #(.CLKHF_DIV("0b00")) SB_HFOSC_INST (// 12MHz
            .CLKHFPU(CLKHFPU), .CLKHFEN(ENACLKM), .CLKHF(HFOSC)) ; 
    SB_I2C_FIFO #(.I2C_SLAVE_ADDR("0b1000001")) SB_I2C_INST_LT /* synthesis I2C_CLK_DIVIDER=374 SDA_INPUT_DELAYED=1 */  (.CLKI(hard_SBCLKi), .CSI(hard_SBCSi[0]), .STBI(hard_SBSTBi), .WEI(hard_SBWRi), .ADRI3(hard_SBADRi[3]), .ADRI2(hard_SBADRi[2]), .ADRI1(hard_SBADRi[1]), .ADRI0(hard_SBADRi[0]), .DATI9(hard_SBDATi[9]), .DATI8(hard_SBDATi[8]), .DATI7(hard_SBDATi[7]), .DATI6(hard_SBDATi[6]), .DATI5(hard_SBDATi[5]), .DATI4(hard_SBDATi[4]), .DATI3(hard_SBDATi[3]), 
                .DATI2(hard_SBDATi[2]), .DATI1(hard_SBDATi[1]), .DATI0(hard_SBDATi[0]), .SCLI(I2C1_SCLi), .SDAI(I2C1_SDAi), .FIFORST(hard_FIFORST), .DATO9(hard0_SBDATo[9]), .DATO8(hard0_SBDATo[8]), .DATO7(hard0_SBDATo[7]), .DATO6(hard0_SBDATo[6]), .DATO5(hard0_SBDATo[5]), .DATO4(hard0_SBDATo[4]), .DATO3(hard0_SBDATo[3]), .DATO2(hard0_SBDATo[2]), .DATO1(hard0_SBDATo[1]), 
                .DATO0(hard0_SBDATo[0]), .ACKO(hard0_SBACKo), .SRWO(hard0_SBSRWo), .I2CIRQ(I2CPIRQ[0]), .I2CWKUP(I2CPWKUP[0]), .SCLO(I2C1_SCLo), .SCLOE(I2C1_SCLoe), .SDAO(I2C1_SDAo), .SDAOE(I2C1_SDAoe), .TXFIFOAEMPTY(TXAEMPTY[0]), .TXFIFOEMPTY(TXEMPTY[0]), .TXFIFOFULL(TXFULL[0]), .RXFIFOEMPTY(RXEMPTY[0]), .RXFIFOAFULL(RXAFULL[0]), .RXFIFOFULL(RXFULL[0]), 
                .MRDCMPL(I2CMRDCMPL[0])) ; 
    assign hard1_SBDATo[9] = 1'b0 ; 
    assign hard1_SBDATo[8] = 1'b0 ; 
    assign hard1_SBDATo[7] = 1'b0 ; 
    assign hard1_SBDATo[6] = 1'b0 ; 
    assign hard1_SBDATo[5] = 1'b0 ; 
    assign hard1_SBDATo[4] = 1'b0 ; 
    assign hard1_SBDATo[3] = 1'b0 ; 
    assign hard1_SBDATo[2] = 1'b0 ; 
    assign hard1_SBDATo[1] = 1'b0 ; 
    assign hard1_SBDATo[0] = 1'b0 ; 
    assign hard1_SBACKo = 1'b0 ; 
    assign hard1_SBSRWo = 1'b0 ; 
    assign I2CPIRQ[1] = 1'b0 ; 
    assign I2CPWKUP[1] = 1'b0 ; 
    assign TXAEMPTY[1] = 1'b0 ; 
    assign TXEMPTY[1] = 1'b0 ; 
    assign TXFULL[1] = 1'b0 ; 
    assign RXEMPTY[1] = 1'b0 ; 
    assign RXAFULL[1] = 1'b0 ; 
    assign RXFULL[1] = 1'b0 ; 
    assign I2CMRDCMPL[1] = 1'b0 ; 
endmodule


