#!/usr/bin/env python3
"""
Plot VoxLink packet CSV logs generated by plotting_log.py.

Expected CSV column order, with or without a header row:
    sample_index, wallclock_s, node, address, command, timestamp, crc,
    q0_raw, q1_raw, q2_raw, q3_raw, q0, q1, q2, q3,
    byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6,
    byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, byte_13

Example:
    python plot_voxlink_csv.py voxlink_packets_20260507_143012.csv
    python plot_voxlink_csv.py voxlink_packets_20260507_143012.csv --out plot.png
    python plot_voxlink_csv.py voxlink_packets_20260507_143012.csv --x timestamp
    python plot_voxlink_csv.py voxlink_packets_20260507_143012.csv --nodes 3 4
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt

CSV_COLUMNS = [
    "sample_index", "wallclock_s", "node", "address", "command", "timestamp", "crc",
    "q0_raw", "q1_raw", "q2_raw", "q3_raw", "q0", "q1", "q2", "q3",
    "byte_0", "byte_1", "byte_2", "byte_3", "byte_4", "byte_5", "byte_6",
    "byte_7", "byte_8", "byte_9", "byte_10", "byte_11", "byte_12", "byte_13",
]

MIN_COLUMNS = len(CSV_COLUMNS)


@dataclass(frozen=True)
class PacketRow:
    sample_index: int
    wallclock_s: float
    node: int
    address: int
    command: int
    timestamp: int
    crc: int
    q0_raw: int
    q1_raw: int
    q2_raw: int
    q3_raw: int
    q0: float
    q1: float
    q2: float
    q3: float
    raw_bytes: tuple[int, ...]


def _is_header_or_comment(row: list[str]) -> bool:
    if not row:
        return True
    first = row[0].strip()
    if not first:
        return True
    if first.startswith("#"):
        return True
    return first.lower() in {"sample_index", "sample", "index"}


def _parse_int(value: str) -> int:
    """Parse decimal or 0x-prefixed integers."""
    return int(value.strip(), 0)


def read_packet_csv(path: Path) -> list[PacketRow]:
    rows: list[PacketRow] = []

    with path.open("r", newline="") as f:
        reader = csv.reader(f)
        for line_number, row in enumerate(reader, start=1):
            if _is_header_or_comment(row):
                continue

            if len(row) < MIN_COLUMNS:
                raise ValueError(
                    f"Line {line_number}: expected at least {MIN_COLUMNS} columns, got {len(row)}"
                )

            try:
                raw_bytes = tuple(_parse_int(v) for v in row[15:29])
                rows.append(
                    PacketRow(
                        sample_index=_parse_int(row[0]),
                        wallclock_s=float(row[1]),
                        node=_parse_int(row[2]),
                        address=_parse_int(row[3]),
                        command=_parse_int(row[4]),
                        timestamp=_parse_int(row[5]),
                        crc=_parse_int(row[6]),
                        q0_raw=_parse_int(row[7]),
                        q1_raw=_parse_int(row[8]),
                        q2_raw=_parse_int(row[9]),
                        q3_raw=_parse_int(row[10]),
                        q0=float(row[11]),
                        q1=float(row[12]),
                        q2=float(row[13]),
                        q3=float(row[14]),
                        raw_bytes=raw_bytes,
                    )
                )
            except ValueError as exc:
                raise ValueError(f"Line {line_number}: could not parse row: {row}") from exc

    if not rows:
        raise ValueError(f"No packet rows found in {path}")

    return rows


def group_by_node(rows: Iterable[PacketRow]) -> dict[int, list[PacketRow]]:
    grouped: dict[int, list[PacketRow]] = {}
    for row in rows:
        grouped.setdefault(row.node, []).append(row)

    for node_rows in grouped.values():
        node_rows.sort(key=lambda r: (r.sample_index, r.wallclock_s))

    return dict(sorted(grouped.items()))


def select_x_values(node_rows: list[PacketRow], x_mode: str) -> list[float | int]:
    if x_mode == "sample":
        return [r.sample_index for r in node_rows]

    if x_mode == "timestamp":
        return [r.timestamp for r in node_rows]

    if x_mode == "time":
        t0 = node_rows[0].wallclock_s
        return [r.wallclock_s - t0 for r in node_rows]

    raise ValueError(f"Unsupported x-axis mode: {x_mode}")


def apply_readout_style(fig, axes) -> None:
    fig.patch.set_facecolor("#1e1e1e")
    for ax in axes:
        ax.set_facecolor("#1e1e1e")
        ax.tick_params(colors="white")
        ax.xaxis.label.set_color("white")
        ax.yaxis.label.set_color("white")
        ax.title.set_color("white")
        ax.grid(True, color="#444444", linestyle="--")


def plot_packets(
    rows: list[PacketRow],
    *,
    nodes: list[int] | None,
    x_mode: str,
    max_points: int,
    dark_style: bool,
    output_path: Path | None,
    show: bool,
) -> None:
    grouped = group_by_node(rows)

    if nodes is not None:
        missing = [n for n in nodes if n not in grouped]
        if missing:
            available = ", ".join(str(n) for n in grouped)
            raise ValueError(f"Requested node(s) not present: {missing}. Available nodes: {available}")
        grouped = {n: grouped[n] for n in nodes}

    node_count = len(grouped)
    fig, axes_grid = plt.subplots(node_count, 1, figsize=(12, 4 * node_count), squeeze=False)
    axes = [axes_grid[idx][0] for idx in range(node_count)]

    if dark_style:
        apply_readout_style(fig, axes)

    for ax, (node, node_rows) in zip(axes, grouped.items()):
        if max_points > 0:
            node_rows = node_rows[-max_points:]

        x = select_x_values(node_rows, x_mode)
        latest = node_rows[-1]

        ax.plot(x, [r.q0 for r in node_rows], color="red",     label="Q0 (X)",    linewidth=1.5)
        ax.plot(x, [r.q1 for r in node_rows], color="lime",    label="Q1 (Y)",    linewidth=1.5)
        ax.plot(x, [r.q2 for r in node_rows], color="cyan",    label="Q2 (Z)",    linewidth=1.5)
        ax.plot(x, [r.q3 for r in node_rows], color="magenta", label="Q3 (Real)", linewidth=1.5)

        ax.set_title(f"Node {node}  —  Logged Quaternion Data")
        ax.set_ylabel("Magnitude (Q14 Float)")
        ax.set_ylim(-1.1, 1.1)

        if x_mode == "time":
            ax.set_xlabel("Time since first logged packet for this node (s)")
        elif x_mode == "sample":
            ax.set_xlabel("Sample Index")
        else:
            ax.set_xlabel("Packet Timestamp")

        legend = ax.legend(facecolor="#1e1e1e" if dark_style else None,
                           edgecolor="white" if dark_style else None,
                           loc="upper right")
        if dark_style:
            for text in legend.get_texts():
                text.set_color("white")

        info = (
            f"Addr: 0x{latest.address:03X}   Cmd: 0x{latest.command:02X}\n"
            f"TS:   {latest.timestamp}\n"
            f"CRC:  0x{latest.crc:04X}\n"
            f"Rows: {len(node_rows)}"
        )
        ax.text(
            0.02,
            0.97,
            info,
            transform=ax.transAxes,
            color="white" if dark_style else "black",
            fontsize=9,
            verticalalignment="top",
            family="monospace",
            bbox=dict(
                facecolor="#1e1e1e" if dark_style else "white",
                edgecolor="#444444" if dark_style else "black",
                alpha=0.9,
            ),
        )

    plt.tight_layout()

    if output_path is not None:
        fig.savefig(output_path, dpi=150, bbox_inches="tight")
        print(f"Saved plot to: {output_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot per-node quaternion data from a VoxLink packet CSV log."
    )
    parser.add_argument("csv_file", type=Path, help="CSV file generated by plotting_log.py")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Optional image output path, e.g. voxlink_plot.png",
    )
    parser.add_argument(
        "--x",
        choices=("time", "sample", "timestamp"),
        default="time",
        help="X-axis source. Default: time",
    )
    parser.add_argument(
        "--nodes",
        type=int,
        nargs="+",
        default=None,
        help="Optional node numbers to plot, e.g. --nodes 3 4",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=0,
        help="Plot only the last N points per node. Default: 0 = all points",
    )
    parser.add_argument(
        "--light",
        action="store_true",
        help="Use Matplotlib's default light theme instead of the readout-style dark theme.",
    )
    parser.add_argument(
        "--save-only",
        action="store_true",
        help="Save the plot without opening an interactive window. Requires --out.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.save_only and args.out is None:
        raise SystemExit("--save-only requires --out")

    rows = read_packet_csv(args.csv_file)
    plot_packets(
        rows,
        nodes=args.nodes,
        x_mode=args.x,
        max_points=args.max_points,
        dark_style=not args.light,
        output_path=args.out,
        show=not args.save_only,
    )


if __name__ == "__main__":
    main()
