M48
; DRILL file {KiCad 9.0.6} date 2025-12-30T15:38:53+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T15:38:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X88.25Y-67.571
X91.25Y-67.571
T2
X97.446Y-73.015
X102.526Y-71.999
X102.526Y-74.031
M30
